"""Update molecule table schema

Revision ID: 334df9d1581f
Revises: 19d69ebdda30
Create Date: 2024-08-26 12:20:53.569345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '334df9d1581f'
down_revision: Union[str, None] = '19d69ebdda30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('molecules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('smiles', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_molecules_id'), 'molecules', ['id'], unique=False)
    op.create_index(op.f('ix_molecules_name'), 'molecules', ['name'], unique=True)
    op.create_index(op.f('ix_molecules_smiles'), 'molecules', ['smiles'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_molecules_smiles'), table_name='molecules')
    op.drop_index(op.f('ix_molecules_name'), table_name='molecules')
    op.drop_index(op.f('ix_molecules_id'), table_name='molecules')
    op.drop_table('molecules')
    # ### end Alembic commands ###
