"""Initial migration

Revision ID: f40f45d70242
Revises: 
Create Date: 2024-10-15 02:24:37.793165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f40f45d70242'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('molecules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('smiles', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_molecules_id'), 'molecules', ['id'], unique=False)
    op.create_index(op.f('ix_molecules_name'), 'molecules', ['name'], unique=True)
    op.create_index(op.f('ix_molecules_smiles'), 'molecules', ['smiles'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_molecules_smiles'), table_name='molecules')
    op.drop_index(op.f('ix_molecules_name'), table_name='molecules')
    op.drop_index(op.f('ix_molecules_id'), table_name='molecules')
    op.drop_table('molecules')
    # ### end Alembic commands ###
