name: Deploy to EC2 Instance

on:
  push:
    branches: [main, ci]
  pull_request:
    branches: [main, ci]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: SSH into EC2 Instance
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: 22
        script: |
          echo "Deploying to EC2 Instance..."
          
          # Ensure Git is installed
          sudo apt-get update
          sudo apt-get install -y git

          # Navigate to the app directory or clone if not present
          if [ ! -d "/home//myproject" ]; then
            echo "Directory not found. Creating it and cloning repository..."
            sudo mkdir -p /home/myproject
            cd /home/myproject
            git clone https://github.com/ggagua/pyforge-python-school-3.git
          else
            cd /home/myproject
            git pull origin main
          fi

          git status
          echo "Repository is up to date."