---
on:
  push:
    branches: [main, ci]
  pull_request:
    branches: [main, ci]
jobs:
  lint_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4
      - name: Set Up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
          pip install flake8
      - name: Run flake8
        run: |
          flake8 . --max-line-length=127 --exit-zero --statistics
  docker-test_job:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5433:5432
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: Copy env.copy to .env
        run: cp env.copy .env

      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=./src" >> $GITHUB_ENV

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -v src/tests
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_SERVER: ${{ secrets.DB_SERVER }}
          DB_PORT: ${{ secrets.DB_PORT }}
          PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
          AIRFLOW_UID: ${{ secrets.AIRFLOW_UID }}