---
on:
  push:
    branches: [main, ci]
  pull_request:
    branches: [main, ci]
jobs:
  lint_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4
      - name: Set Up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
          pip install flake8
      - name: Run flake8
        run: |
          flake8 . --max-line-length=127 --exit-zero --statistics
  docker_test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4
      - name: Build Docker Image
        run: |
          docker build --no-cache -t my-app -f src/Dockerfile src/
      - name: Run Tests in Docker Container
        run: |
          docker run --rm my-app python -m pytest src/pytest_main.py
